version: '3'

services:
  db:
    container_name: my_psql
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      scrap:
        ipv4_address: 10.5.0.5

  scrappy:
    container_name: my_scrappy
    build: scrappy/.
    image: daguito81/dynamic_data_web_scraping:latest
    networks:
      scrap:
        ipv4_address: 10.5.0.6
    depends_on:
      - db
networks:
  scrap:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
volumes:
  db-data:
